### ISSUE TITLE
[grpc-gateway] upstream sent no valid HTTP/1.0 header while reading response header from upstream

### ISSUE THREAD

**Issue by Notailli** [Kong/kong#11274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.8

### Current Behavior

配置grpc-gateway，grpc demo报错 Unexpected HTTP/1.x request: POST /demo/v1/messages/kong2.2
kong-proxy 报错：upstream sent no valid HTTP/1.0 header while reading response header from upstream, client: 172.31.152.192, server: kong, request: "GET /demo/v1/messages/kong2.2 HTTP/1.1", upstream: "http://172.31.167.197:6565/demo/v1/messages/kong2.2", host: "kong.grpc.com"

### Expected Behavior

可以通过http请求，转发到grpc服务中

### Steps To Reproduce

# 相关配置如下，已将hello.proto文件放到了kong-proxy的/usr/local/kong目录下面
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
spec:
  ingressClassName: kong
  rules:
  - host: kong.grpc.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: grpc-demo
            port:
              number: 6565
```

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: grpc-gateway-example
plugin: grpc-gateway
config:
  proto: /usr/local/kong/hello.proto
```

```
 apiVersion: v1
kind: Service
metadata:
  labels:
    name: grpc-demo
    system/appName: grpc-demo
  name: grpc-demo
spec:
  clusterIP: 10.105.182.181
  clusterIPs:
  - 10.105.182.181
  ports:
  - name: tcp-port-0
    port: 8089
    protocol: TCP
    targetPort: 8089
  - name: tcp-port-1
    port: 6565
    protocol: TCP
    targetPort: 6565
  selector:
    name: grpc-demo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}


---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: grpc-demo
    name: grpc-demo
    version: v1
  name: grpc-demo
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grpc-demo
      name: grpc-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv4pools: '["172.31.0.0/16"]'
        sidecar.istio.io/inject: "false"
        system/container-registry-map: '{"grpc-demo":"UPID-KGRrbyfedb64"}'
        system/registry: default
        v1.multus-cni.io/default-network: kube-system/calico@eth0
      creationTimestamp: null
      labels:
        app: grpc-demo
        name: grpc-demo
        version: v1
    spec:
      containers:
      - image: xxxx/grpc-demo:1.0
        imagePullPolicy: IfNotPresent
        name: grpc-demo
        ports:
        - containerPort: 8089
          protocol: TCP
        - containerPort: 6565
          protocol: TCP
```

## hello.proto文件
```
syntax = "proto2";

option java_multiple_files = true;
package io.github.hundanli.grpc.greeter.hello;
import "google/protobuf/timestamp.proto";

service HelloService {
  rpc hola(HelloRequest) returns (HelloResponse){
    option (google.api.http) = {
      get: "/demo/v1/messages/{name}"
    };
  }
}

// The request message containing the user's name.
message HelloRequest {
  required string name = 1;
}

// The response message containing the greetings
message HelloResponse {
  required string message = 1;
}
```

# kong-proxy报错
```
2023/07/25 10:42:52 [error] 1116#0: *31165 upstream sent no valid HTTP/1.0 header while reading response header from upstream, client: 172.31.152.192, server: kong, request: "GET /demo/v1/messages/kong2.2 HTTP/1.1", upstream: "http://172.31.167.197:6565/demo/v1/messages/kong2.2", host: "kong.grpc.com"
172.31.152.192 - - [25/Jul/2023:10:42:52 +0800] "GET /demo/v1/messages/kong2.2 HTTP/1.1" 009 0 "-" "curl/7.29.0"
```

# grpc demo报错
```
2023-07-25 02:42:52.315  INFO 1 --- [-worker-ELG-3-1] i.g.n.NettyServerTransport.connections   : Transport failed

io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: POST /demo/v1/messages/kong2.2
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85) ~[netty-codec-http2-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:314) ~[netty-codec-http2-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251) ~[netty-codec-http2-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450) ~[netty-codec-http2-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628) ~[netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:528) ~[netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:482) ~[netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) ~[netty-transport-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-common-4.1.29.Final.jar!/:4.1.29.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.29.Final.jar!/:4.1.29.Final]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

### Anything else?

kong 2.8

**Comment by StarlightIbuki** [comment]
You need to configure the service with protocol grpc.
Reference: https://docs.konghq.com/hub/kong-inc/grpc-gateway/how-to/#:~:text=services%3A%0A%2D-,protocol%3A%20grpc,-host%3A%20localhost

**Comment by theocerutti** [comment]
What I did to resolve this:
* make sure microservice listen to 0.0.0.0
* make sure that is konghq.com/protocol for service and konghq/protocols (with "s") for ingresses
* you should have 2 ingresses: 1 HTTP with grpc-gateway (konghq/plugins: my-grpc-gateway, you have to create a KongPlugin with proto path file, this proto file must be inside the kong gateway) + 1 GRPC ingress
* i removed all grpcs (with "s") protocols

**Comment by StarlightIbuki** [comment]
Looks like you have resolved the issue. Closing the ticket. Please feel free to reopen if we have further concerns.
