### ISSUE TITLE
Kong doesn't support default ssl library

### ISSUE THREAD

**Issue by scw00** [Kong/kong#4973]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

Kong doesn't support default ssl library

### Steps To Reproduce

run 
```
kong start -c kong.conf
```

### Additional Details & Logs

- Kong version (`$ kong version`) latest
- Kong debug-level startup logs (`$ kong start --vv`) no long
- Kong error logs (`<KONG_PREFIX>/logs/error.log`) no log
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system Ubuntu16.04

```
(gdb) bt full
#0  0x00007fbea7d45a70 in ssl3_ctx_ctrl () from /usr/lib64/libssl.so.10
No symbol table info available.
#1  0x00007fbea7fb04ad in sx_new () from /usr/local/lib/lua/5.1/_openssl.so
No symbol table info available.
#2  0x00007fbea997755a in lj_BC_FUNCC () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
No symbol table info available.
#3  0x00007fbea99ccdaa in lj_cf_package_require (L=0x7fbeaa407c68) at lib_package.c:459
        name = 0x7fbeaa3d4718 "http.tls"
        i = 1
#4  0x00007fbea997755a in lj_BC_FUNCC () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
No symbol table info available.
#5  0x00007fbea99ccdaa in lj_cf_package_require (L=0x7fbeaa407c68) at lib_package.c:459
        name = 0x7fbeaa422180 "kong.conf_loader"
        i = 3
#6  0x00007fbea997755a in lj_BC_FUNCC () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
No symbol table info available.
#7  0x00007fbea99ccdaa in lj_cf_package_require (L=0x7fbeaa407c68) at lib_package.c:459
        name = 0x7fbeaa41bd68 "kong.cmd.start"
        i = 3
#8  0x00007fbea997755a in lj_BC_FUNCC () from /usr/local/openresty/luajit/lib/libluajit-5.1.so.2
No symbol table info available.
#9  0x00000000005310b4 in ngx_http_lua_run_thread (L=L@entry=0x7fbeaa432378, r=r@entry=0xd28c70, ctx=ctx@entry=0xd28180, nrets=<optimized out>, nrets@entry=1)
    at ../ngx_lua-0.10.15/src/ngx_http_lua_util.c:1091
        next_coctx = <optimized out>
        parent_coctx = <optimized out>
        orig_coctx = 0xd281a8
        rv = <optimized out>
        success = <optimized out>
        next_co = <optimized out>
        old_co = <optimized out>
        err = <optimized out>
        msg = <optimized out>
        trace = <optimized out>
        rc = <optimized out>
        old_pool = 0x0
#10 0x0000000000548d36 in ngx_http_lua_timer_handler (ev=<optimized out>) at ../ngx_lua-0.10.15/src/ngx_http_lua_timer.c:705
        n = 2
        rc = <optimized out>
        c = 0xcef430
        r = 0xd28c70
        cln = <optimized out>
        pcln = <optimized out>
        tctx = {main_conf = <optimized out>, srv_conf = <optimized out>, loc_conf = <optimized out>, co = 0x7fbeaa407c68, pool = <optimized out>, listening = <optimized out>, client_addr_text = {
            len = <optimized out>, data = <optimized out>}, lmcf = <optimized out>, vm_state = <optimized out>, co_ref = <optimized out>, delay = <optimized out>, premature = <optimized out>}
        lmcf = <optimized out>
        clcf = <optimized out>
#11 0x0000000000487192 in ngx_event_expire_timers () at src/event/ngx_event_timer.c:97
        ev = 0xd21e70
        root = <optimized out>
---Type <return> to continue, or q <return> to quit---
        sentinel = 0xabc660 <ngx_event_timer_sentinel>
#12 0x0000000000486e18 in ngx_process_events_and_timers (cycle=cycle@entry=0xceb1a0) at src/event/ngx_event.c:266
        flags = 1
        timer = <optimized out>
        delta = 6
        q = <optimized out>
        ev = <optimized out>
#13 0x000000000048f2e3 in ngx_single_process_cycle (cycle=cycle@entry=0xceb1a0) at src/os/unix/ngx_process_cycle.c:333
        i = <optimized out>
#14 0x0000000000468999 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:379
        b = <optimized out>
        log = <optimized out>
        i = <optimized out>
        cycle = 0xceb1a0
        init_cycle = {conf_ctx = 0x0, pool = 0xce9b20, log = 0xab9f20 <ngx_log>, new_log = {log_level = 0, file = 0x0, connection = 0, disk_full_time = 0, handler = 0x0, data = 0x0, writer = 0x0,
            wdata = 0x0, action = 0x0, next = 0x0}, log_use_stderr = 0, files = 0x0, free_connections = 0x0, free_connection_n = 0, modules = 0x0, modules_n = 0, modules_used = 0,
          reusable_connections_queue = {prev = 0x0, next = 0x0}, reusable_connections_n = 0, listening = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, paths = {elts = 0x0, nelts = 0,
            size = 0, nalloc = 0, pool = 0x0}, config_dump = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, config_dump_rbtree = {root = 0x0, sentinel = 0x0, insert = 0x0},
          config_dump_sentinel = {key = 0, left = 0x0, right = 0x0, parent = 0x0, color = 0 '\000', data = 0 '\000'}, open_files = {last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0,
            nalloc = 0, pool = 0x0}, shared_memory = {last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, connection_n = 0, files_n = 0, connections = 0x0,
          read_events = 0x0, write_events = 0x0, old_cycle = 0x0, conf_file = {len = 37, data = 0xce9b70 "\251\254", <incomplete sequence \316>}, conf_param = {len = 0, data = 0x0}, conf_prefix = {
            len = 27, data = 0xce9b70 "\251\254", <incomplete sequence \316>}, prefix = {len = 22, data = 0x7ffcd9443f13 "/tmp/resty_GcjlqXgHOT/"}, lock_file = {len = 0, data = 0x0}, hostname = {
            len = 0, data = 0x0}, intercept_error_log_handler = 0x0, intercept_error_log_data = 0x0, entered_logger = 0}
        cd = <optimized out>
        ccf = <optimized out>
(gdb)
(gdb) q
```

I built another openssl but it seems lua script doesn't load my newest openssl library.

**Comment by scw00** [comment]
```
[root@master68 bin]# ldd _openssl.so.bak
	linux-vdso.so.1 =>  (0x00007ffc155d2000)
	libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007fa35c604000)
	libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007fa35c1a3000)
	libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007fa35bf87000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00007fa35bc85000)
	libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007fa35ba81000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00007fa35b6b4000)
	libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2 (0x00007fa35b467000)
	libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007fa35b17e000)
	libcom_err.so.2 => /usr/lib64/libcom_err.so.2 (0x00007fa35af7a000)
	libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x00007fa35ad47000)
	libz.so.1 => /usr/lib64/libz.so.1 (0x00007fa35ab31000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa35caa9000)
	libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 (0x00007fa35a921000)
	libkeyutils.so.1 => /usr/lib64/libkeyutils.so.1 (0x00007fa35a71d000)
	libresolv.so.2 => /usr/lib64/libresolv.so.2 (0x00007fa35a504000)
	libselinux.so.1 => /usr/lib64/libselinux.so.1 (0x00007fa35a2dd000)
	libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007fa35a07b000)

```

**Comment by scw00** [comment]
luaossl-20170903 fixed that.

**Comment by james-callahan** [comment]
> I built another openssl but it seems lua script doesn't load my newest openssl library.

How did you build your own openssl? Various kong components/dependencies will need to be rebuilt against your different openssl version.

**Comment by scw00** [comment]
./config with newest openssl version. And then reinstall luaossl .

**Comment by dndx** [comment]
@scw00 do not build Kong's dependencies manually. If you must consider using [openresty-build-tools](https://github.com/Kong/openresty-build-tools) instead. Also like @james-callahan said all Lua C dependencies has to be rebuild as well.

**Comment by scw00** [comment]
I fixed this case  after rebuild luaossl. But sometime it doesn't work. Will re-open if I re-product this.
