### ISSUE TITLE
[Cassandra] Operation timed out when run kong migrations bootstrap

### ISSUE THREAD

**Issue by mrpk1906** [Kong/kong#7451]
### Summary
- Kong version 2.4.1
- Cassandra Multi DC (6 nodes): 3 on each DC
- When I bootstrap a new cluster, i got a time out error

```
Error: [Cassandra error] cluster_mutex callback threw an error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:41: [Cassandra error] failed to run migration '013_220_to_230' up: [Write timeout] Operation timed out - received only 1 responses.
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:41: in function </usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:40>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/db/init.lua:402: in function </usr/local/share/lua/5.1/kong/db/init.lua:352>
	[C]: in function 'pcall'
	/usr/local/share/lua/5.1/kong/concurrency.lua:45: in function 'cluster_mutex'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:40: in function 'bootstrap'
	/usr/local/share/lua/5.1/kong/cmd/migrations.lua:162: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>

  Run with --v (verbose) or --vv (debug) for more details
```

I tried run several times but got the same error

### Kong config

```
cassandra_repl_strategy = NetworkTopologyStrategy
cassandra_data_centers = dc1:3,dc2:3
cassandra_schema_consensus_timeout = 60000
```

**Comment by mikefero** [comment]
Hello @mrpk1906,

I have a couple of questions for you and some possible recommendations: 

- What version of Apache Cassandra are you running (shouldn't matter, but will be helpful to re-create your exactly setup if needed later)?
- Have you properly configured your [Cassandra configuration settings](https://docs.konghq.com/gateway-oss/2.4.x/configuration/#cassandra-settings) for Kong Gateway OSS; load balancing policy, consistency levels, and replication factor?
  - `cassandra_lb_policy` or `KONG_CASSANDRA_LB_POLICY` should be `DCAwareRoundRobin` with `cassandra_local_datacenter` or `KONG_CASSANDRA_LOCAL_DATACENTER` being assigned the name of your local Cassandra datacenter (e.g. `dc1` or `dc2` depending).
  - `cassandra_write_consistency`/`cassandra_read_consistency` or `KONG_CASSANDRA_WRITE_CONSISTENCY`/`KONG_CASSANDRA_READ_CONSISTENCY` should be set to `LOCAL_QUORUM`
  - `db_update_propagation` or `KONG_DB_UPDATE_PROPAGATION` should be greater than the default `0` (e.g. `30` seconds is good start for Cassandra, but the actual value will be dependent on your resources available and your configuration or Cassandra).

These above Cassandra configuration settings for the Kong Gateway OSS should correct the migrations issues you are seeing and get everything up and running.

**Comment by mrpk1906** [comment]
Hello @mikefero,

* I'm using Cassandra 3.11.10
* cassandra_lb_policy: `RequestDCAwareRoundRobin`
* cassandra_local_datacenter: `dc2` (i'm running migrations from a node in DC2)
* cassandra_write_consistency and cassandra_read_consistency: LOCAL_QUORUM
* db_update_propagation: current is `2`, i tried to change to `30` following your recommendation but not success, i got the same error.

Then I ran `migrations up`, it seems ok

```
root@kong-node2:~# kong migrations bootstrap --db-timeout=200 --lock-timeout=200
Bootstrapping database...
migrating core on keyspace 'kong_db'...
core migrated up to: 000_base (executed)
core migrated up to: 003_100_to_110 (executed)
core migrated up to: 004_110_to_120 (executed)
core migrated up to: 005_120_to_130 (executed)
core migrated up to: 006_130_to_140 (executed)
core migrated up to: 007_140_to_150 (executed)
core migrated up to: 008_150_to_200 (executed)
core migrated up to: 009_200_to_210 (executed)
core migrated up to: 010_210_to_211 (executed)
core migrated up to: 011_212_to_213 (executed)
core migrated up to: 012_213_to_220 (executed)
Error: [Cassandra error] cluster_mutex callback threw an error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:41: [Cassandra error] failed to run migration '013_220_to_230' up: [Write timeout] Operation timed out - received only 1 responses.
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:41: in function </usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:40>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/db/init.lua:402: in function </usr/local/share/lua/5.1/kong/db/init.lua:352>
	[C]: in function 'pcall'
	/usr/local/share/lua/5.1/kong/concurrency.lua:45: in function 'cluster_mutex'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:40: in function 'bootstrap'
	/usr/local/share/lua/5.1/kong/cmd/migrations.lua:162: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>

  Run with --v (verbose) or --vv (debug) for more details
root@kong-node2:~# kong migrations bootstrap --db-timeout=200 --lock-timeout=200
Database already bootstrapped
root@kong-node2:~# kong migrations up
migrating core on keyspace 'kong_db'...
core migrated up to: 013_220_to_230 (executed)
migrating acl on keyspace 'kong_db'...
acl migrated up to: 000_base_acl (executed)
acl migrated up to: 002_130_to_140 (executed)
acl migrated up to: 003_200_to_210 (pending)
acl migrated up to: 004_212_to_213 (pending)
migrating acme on keyspace 'kong_db'...
acme migrated up to: 000_base_acme (executed)
migrating basic-auth on keyspace 'kong_db'...
basic-auth migrated up to: 000_base_basic_auth (executed)
basic-auth migrated up to: 002_130_to_140 (executed)
basic-auth migrated up to: 003_200_to_210 (pending)
migrating bot-detection on keyspace 'kong_db'...
bot-detection migrated up to: 001_200_to_210 (pending)
migrating hmac-auth on keyspace 'kong_db'...
hmac-auth migrated up to: 000_base_hmac_auth (executed)
hmac-auth migrated up to: 002_130_to_140 (executed)
hmac-auth migrated up to: 003_200_to_210 (pending)
migrating ip-restriction on keyspace 'kong_db'...
ip-restriction migrated up to: 001_200_to_210 (pending)
migrating jwt on keyspace 'kong_db'...
jwt migrated up to: 000_base_jwt (executed)
jwt migrated up to: 002_130_to_140 (executed)
jwt migrated up to: 003_200_to_210 (pending)
migrating key-auth on keyspace 'kong_db'...
key-auth migrated up to: 000_base_key_auth (executed)
key-auth migrated up to: 002_130_to_140 (executed)
key-auth migrated up to: 003_200_to_210 (pending)
migrating oauth2 on keyspace 'kong_db'...
oauth2 migrated up to: 000_base_oauth2 (executed)
oauth2 migrated up to: 003_130_to_140 (executed)
oauth2 migrated up to: 004_200_to_210 (pending)
oauth2 migrated up to: 005_210_to_211 (pending)
migrating rate-limiting on keyspace 'kong_db'...
rate-limiting migrated up to: 000_base_rate_limiting (executed)
rate-limiting migrated up to: 003_10_to_112 (executed)
rate-limiting migrated up to: 004_200_to_210 (executed)
migrating response-ratelimiting on keyspace 'kong_db'...
response-ratelimiting migrated up to: 000_base_response_rate_limiting (executed)
migrating session on keyspace 'kong_db'...
session migrated up to: 000_base_session (executed)
session migrated up to: 001_add_ttl_index (executed)
30 migrations processed
20 executed
10 pending

Database has pending migrations; run 'kong migrations finish' when ready
```

**Comment by mikefero** [comment]
I wasn't able to reproduce the issue using your setup, try running `kong migrations reset -y` before executing `kong migrations bootstrap` to drop the `kong` schema in Cassandra cluster.

Here are the steps I used to attempt to reproduce the issue:

### Create Apache Cassandra Cluster

Create a 6 node Cassandra v3.11.10 cluster with 2 datacenters using [CCM](https://github.com/riptano/ccm)

```
ccm create -v 3.11.10 -n 3:3 -s cass-3-11-10-3-3-nodes
```

### Start a Kong Gateway OSS instance

Start a Kong Gateway OSS v2.4.1 instance using [Gojira](https://github.com/Kong/gojira) that will utilize the Cassandra cluster created in the previous step

```
KONG_DATABASE=cassandra \
KONG_TEST_DATABASE=cassandra \
  gojira up \
         --network-mode host \
         --alone \
         --image kong:2.4.1-alpine
```

### Bootstrap the Kong Gateway OSS

```
gojira run \
       --network-mode host \
       --alone \
       --image kong:2.4.1-alpine \
       -e KONG_CASSANDRA_REPL_STRATEGY=NetworkTopologyStrategy \
       -e KONG_CASSANDRA_DATA_CENTERS=dc1:3,dc2:3 \
       -e KONG_CASSANDRA_SCHEMA_CONSENSUS_TIMEOUT=60000 \
       -e KONG_CASSANDRA_WRITE_CONSISTENCY=LOCAL_QUORUM \
       -e KONG_CASSANDRA_READ_CONSISTENCY=LOCAL_QUORUM \
       -e KONG_CASSANDRA_LB_POLICY=RequestDCAwareRoundRobin \
       -e KONG_CASSANDRA_LOCAL_DATACENTER=dc2 \
       -e KONG_DB_UPDATE_PROPAGATION=2 \
       kong migrations bootstrap
```

**Comment by mrpk1906** [comment]
Hello @mikefero,

Below is Cassandra logs when bootstrap timed out:

```
INFO  [MigrationStage:1] 2021-06-14 23:54:08,642 ColumnFamilyStore.java:421 - Initializing apigw_service.clustering_data_planes
WARN  [MessagingService-Incoming-/10.2.2.100] 2021-06-14 23:54:11,377 IncomingTcpConnection.java:107 - UnknownColumnFamilyException reading from socket; closing
org.apache.cassandra.db.UnknownColumnFamilyException: Couldn't find table for cfId 2463e470-cd31-11eb-8b24-359a87672850. If a table was just created, this is likely due to the schema not being fully propagated.  Please wait for schema agreement on table creation.
	at org.apache.cassandra.config.CFMetaData$Serializer.deserialize(CFMetaData.java:1578) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.db.partitions.PartitionUpdate$PartitionUpdateSerializer.deserialize30(PartitionUpdate.java:913) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.db.partitions.PartitionUpdate$PartitionUpdateSerializer.deserialize(PartitionUpdate.java:888) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.service.paxos.Commit$CommitSerializer.deserialize(Commit.java:136) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.service.paxos.Commit$CommitSerializer.deserialize(Commit.java:118) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.net.MessageIn.read(MessageIn.java:123) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.net.IncomingTcpConnection.receiveMessage(IncomingTcpConnection.java:207) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.net.IncomingTcpConnection.receiveMessages(IncomingTcpConnection.java:195) ~[apache-cassandra-3.11.10.jar:3.11.10]
	at org.apache.cassandra.net.IncomingTcpConnection.run(IncomingTcpConnection.java:98) ~[apache-cassandra-3.11.10.jar:3.11.10]
INFO  [MigrationStage:1] 2021-06-14 23:54:11,474 ColumnFamilyStore.java:421 - Initializing apigw_service.parameters
```

**Comment by mikefero** [comment]
```
INFO  [MigrationStage:1] 2021-06-14 23:54:08,642 ColumnFamilyStore.java:421 - Initializing apigw_service.clustering_data_planes
WARN  [MessagingService-Incoming-/10.2.2.100] 2021-06-14 23:54:11,377 IncomingTcpConnection.java:107 - UnknownColumnFamilyException reading from socket; closing
org.apache.cassandra.db.UnknownColumnFamilyException: Couldn't find table for cfId 2463e470-cd31-11eb-8b24-359a87672850. If a table was just created, this is likely due to the schema not being fully propagated.  Please wait for schema agreement on table creation.
```

You might need to increase the schema agreement/consensus timeout and look into the Apache Cassandra debug logs for any slow query operations; Cassandra is known to bootstrap slower than PostgreSQL.

One Cassandra tuning note to eek out some additional performance would be to ensure you are using a smaller amount of vnodes than the default 256 as this is known to create some significant slowdown in a Cassandra cluster. Both [DataStax](https://docs.datastax.com/en/cassandra-oss/3.x/cassandra/architecture/archDataDistributeVnodesUsing.html) and [Instaclutr](https://www.instaclustr.com/cassandra-vnodes-how-many-should-i-use/) have some good write-ups for tuning this value; DataStax recommends 8 while Instaclustr recommends 16. There are lots of knobs and switches to help fine tune Cassandra in your environment.

**Comment by mrpk1906** [comment]
Hi @mikefero,

Thanks for your help

I tried change num_tokens to 8 following your recommendation
I changed cassandra *timeout setting in config:

```
  read_request_timeout_in_ms: 120000
  range_request_timeout_in_ms: 120000
  write_request_timeout_in_ms: 120000
  counter_write_request_timeout_in_ms: 10000
  cas_contention_timeout_in_ms: 10000
  truncate_request_timeout_in_ms: 120000
  request_timeout_in_ms: 120000
```

I was ran bootstrap command with `--db-timeout=120 --lock-timeout=120` too, but still got timeout error

From file `/usr/local/share/lua/5.1/kong/db/migrations/core/013_220_to_230.lua`, I saw it just run simple query

I don't know why it always timed out at this migration :(

**Comment by mikefero** [comment]
Is there anything in the Cassandra debug logs that might help narrow down the issue?

**Comment by mrpk1906** [comment]
Hi @mikefero,

I think my issue is at this query in `/usr/local/share/lua/5.1/kong/db/migrations/core/013_220_to_230.lua`

```
INSERT INTO parameters (key, value) VALUES('cluster_id', '%s')
IF NOT EXISTS;
```

I tried change code in `013_220_to_230.lua` following

```
  cassandra = {
    up = [[
      CREATE TABLE IF NOT EXISTS parameters(
        key            text,
        value          text,
        created_at     timestamp,
        PRIMARY KEY    (key)
      );

      ALTER TABLE certificates ADD cert_alt TEXT;
      ALTER TABLE certificates ADD key_alt TEXT;
      ALTER TABLE clustering_data_planes ADD version text;
      ALTER TABLE clustering_data_planes ADD sync_status text;
    ]],
    teardown = function(connector)
      local coordinator = assert(connector:get_stored_connection())
      local _, err = coordinator:execute(string.format("INSERT INTO parameters (key, value) VALUES('cluster_id', '%s') IF NOT EXISTS;", CLUSTER_ID))
      if err then
        return nil, err
      end

      return true
    end
  }
```

Then it ran successfully

```
...
core migrated up to: 011_212_to_213 (executed)
core migrated up to: 012_213_to_220 (executed)
core migrated up to: 013_220_to_230 (executed)
migrating acl on keyspace 'kong_db'...
acl migrated up to: 000_base_acl (executed)
acl migrated up to: 002_130_to_140 (executed)
acl migrated up to: 003_200_to_210 (executed)
acl migrated up to: 004_212_to_213 (executed)
...
```

**Comment by mikefero** [comment]
This sounds like the `CREATE TABLE` propagated through in the C* cluster eventually which is why this change allowed the `INSERT` request to finally execute with the defined consistency during the `teardown` phase. It still seems like there is some latency going on in your C* cluster, but I don't see this change breaking anything either.

I recommend opening up a pull request with this change, reference this issue, and get a review going from other to ensure that no breaking changes are being introduced.

Glad you were able to get things going!!!
